#Monodb Configuration
spring:
  data:
    mongodb:
      database: wms
      #username:
      #password:
      host: localhost
      port: 27017
  mongodb:
    embedded:
      version: 3.2.2
      features: ONLY_WITH_SSL, ONLY_WINDOWS_2008_SERVER

logging:
  level:
    com.silaev.wms: DEBUG

storage:
  bulk-upload-path: uploads/files